### ISSUE TITLE
[OPENGL] Viewer consistently flips to empty viewer

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#10]
**Platform**
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Summary**
Loading sample footage will consistently drop the footage to an empty viewer after a brief bit of sliding strips.

**Additional Information / Output**
```
[WARNING] OpenGLTexture::Upload() called while it wasn't created ((null):0)
[WARNING] OpenGLTexture::Upload() called while it wasn't created ((null):0)
[WARNING] OpenGLTexture::Upload() called while it wasn't created ((null):0)
[...]
```

**Comment by itsmattkc** [comment]
I haven't been able to recreate this, and judging by the nature of the error I'm going to assume this has been corrected by later advancements. If it still occurs, let me know.
