### ISSUE TITLE
[CRASH] Change Colour Picker display colour space

### ISSUE THREAD

**Issue by AlexMitchellMus** [sobotka/olive#106]
**Summary**
Changing colour output space of colour picker

**Additional Information / Output**
Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.6.8-arch1-1
System: Arch Linux (arch unknown)

./olive-editor(+0xf0839)[0x55e8aac92839]
/usr/lib/libc.so.6(+0x3bd70)[0x7f4a4ce46d70]
/usr/lib/libc.so.6(gsignal+0x145)[0x7f4a4ce46ce5]
/usr/lib/libc.so.6(abort+0x12b)[0x7f4a4ce30857]
/usr/lib/libstdc++.so.6(+0x9681d)[0x7f4a4d1c981d]
/usr/lib/libstdc++.so.6(+0xa32ca)[0x7f4a4d1d62ca]
/usr/lib/libstdc++.so.6(+0xa3337)[0x7f4a4d1d6337]
/usr/lib/libstdc++.so.6(+0xa359e)[0x7f4a4d1d659e]
/usr/lib/libOpenColorIO.so.1(+0x27812)[0x7f4a4f670812]
/usr/lib/libOpenColorIO.so.1(+0xd4fb4)[0x7f4a4f71dfb4]
Version: 42907973
Signal: 6

**Comment by itsmattkc** [comment]
Fixed in 30efe054c70e4b642ffad19f93550ea38d31eca1
