### ISSUE TITLE
[TODO] Auto-set render resolution based on viewer dimensions

### ISSUE THREAD

**Issue by itsmattkc** [sobotka/olive#109]
**General TODO Summary**
Renders always default to 1/2 resolution, fine for 1080p, but cumbersome at 4K. The viewer could easily auto-select an appropriate resolution based on its viewport size.

**Comment by sobotka** [comment]
I _think_ we can unify the entire offline pipeline in truth. That is, the offline base resolution should be constant, across the ingestion cache dimensions, and the render cache, etc. Perhaps there's some room here to provide for an ingestion cache downresing as well, allowing for a percentage to maximum ingestion cache?

Worth pondering a bit.

Cons:
* Changing the offline resolution would result in the footage requiring re-caching in the ingestion cache. Rare case?

Pros:
* Homogenize the entire stack, allowing for clarity of settings for audience, as well as streamlined rendering pipeline.

**Comment by itsmattkc** [comment]
I don't disagree, perhaps a "maximum offline resolution" could be set in the project properties (e.g. 960x540) and the software will use the sequence aspect ratio to fit within that size (16:9 sequences will reach 960x540, 4:3 sequences will reach 720x540).

Changing the viewer "divider" already requires a re-cache so the con remains the same. However the advantage of something like this is the render will always take place within known constraints, no matter what the final resolution is.
