### ISSUE TITLE
[CACHE] Cache doesn't get cleaned

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#11]
**Platform**

Ubuntu 19.10 64-bit

**Summary**

When I click 'Clear Disk Cache' in the Preferences dialog, Olive tells me that the cache is now cleaned. However, the local mediaindex folder is still full and exceeds 20GB set by default.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Should be fixed in 3f85ce8a7ad8ba06185b62c67bd319495d416fa1
