### ISSUE TITLE
[CI] AppVeyor fails due to "exceeding maximum allowed artifact storage size"

### ISSUE THREAD

**Issue by itsmattkc** [sobotka/olive#118]
**Summary**
All `master` AppVeyor builds appear to be failing due to the following error message:
> Maximum allowed artifact storage size of 50000 Mb will be exceeded.

While at first glance, this seems odd since Olive is not larger than 50GB (or 50Gb) in size, this appears to be actually referring **overall** artifact storage. That is, we actually commit so much that we've consumed 50GB of storage total on AppVeyor's servers. Good job, everyone.

Unfortunately AppVeyor apparently does not expose functionality to manually delete artifacts. According to [this thread on their support forum](https://help.appveyor.com/discussions/problems/18191-setting-autodelete-policies-for-deleting-old-artifacts), the solution appears to require contacting AppVeyor directly and they'll increase the maximum storage limit. Seems unnecessary considering the vast, vast majority of those artifacts are useless to us, but anyways that seems to be what we need to do.

**Comment by sobotka** [comment]
This is so dumb. No way to automatically delete expired builds? Time offset?

**Comment by itsmattkc** [comment]
Their "policy" auto-deletes after 6 months, but there seems to be no control over it and no way to manually delete old artifacts.

In theory we could just disable AppVeyor artifacts since we upload to GitHub Releases anyway? Not sure how people feel about that.

**Comment by Simran-B** [comment]
Would still be useful to have CI builds for PRs. Can you contact their support to ask for a shorter retention time? One month should be long enough.

Artifacts can be pushed from within the build script, so it would be possible to check some conditions like the commit message and only upload if it starts with "/CI" for instance. For master it can be skipped entirely because of the GitHub continuous release as you say.

**Comment by Simran-B** [comment]
Is this available to you Matt? Or is it only in their Enterprise version?

![Screenshot_20200509-095242__01](https://user-images.githubusercontent.com/7819991/81467728-f060df80-91da-11ea-9185-aaf42b87641c.jpg)

**Comment by itsmattkc** [comment]
@Simran-B Doesn't look like it, these are the only options I get:
![image](https://user-images.githubusercontent.com/34096995/81468290-e6ae9a80-9221-11ea-88c2-f4984989e2e0.png)

Generally I'm leaning towards AppVeyor artifacts aren't necessary. They're only Windows builds which aren't useful for a lot of us, and PRs aren't particularly hard to compile/test once you have a development environment set up.

**Comment by itsmattkc** [comment]
I believe this is superseded by #126
