### ISSUE TITLE
[TODO] Choose between DVL and regular colour space

### ISSUE THREAD

**Issue by ThomasWilshaw** [sobotka/olive#119]
**General TODO Summary**
Add fourth entry to ManagedDisplayWidget that turns off DVL and lets you apply a chosen colour space (e.g. Arri Wide Gamut LogC). Selecting again turns DVL back on and turns off the chosen colour space.

**Additional Information / Notes**
I had been wondering for a while if it would be better to make the chosen CM permanently visible in the playback widgets in some way, rather than through the right click menu. It would be perhaps nicer here as you could then have some kind of selector and grey out whichever wasn't selected. It would make it harder to accidentally be using the wrong CM.

**Comment by itsmattkc** [comment]
Done in 0f301cfdcc65da9ed5bcacfff6ac2d9b888a9710
