### ISSUE TITLE
[OPENGL] Crash after clicking one of the Nodes in the node viewport

### ISSUE THREAD

**Issue by Corruptinator** [sobotka/olive#12]
**Platform**
Windows 10 Pro 64-bit (Custom PC) Ryzen 9 3900x, Nvidia RTX 2080 Super

**Summary**
For some reason when I click on a node in the node viewport, Olive freezes for a few seconds and then it crashes.

**Comment by itsmattkc** [comment]
Known issue, happens with Track and Viewer nodes.

**Comment by itsmattkc** [comment]
Fixed in 785160b86bce49dbd44dc2ab429ced38e9281a36
