### ISSUE TITLE
[CRASH] Multiple Proxy Ingestion Ceases System

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#125]
**Platform**

Debian Buster, amd64

**Summary**

Loading multiple heavier Arri footage sequences and attempting to proxy / ingestion cache them ceases the machine, eventually SIGKILLing with not available backtrace.

**Additional Information / Output**

Used test footage:
```
A001C001_200410_R0ZV.mov
A001C002_200410_R0ZV.mov
A001C003_200410_R0ZV.mov
J001C012_140110_R6MS.mov
B001C003_180327_R1ZA.mov
B001C005_180327_R1ZA.mov
B001C010_180327_R1ZA.mov
```

**Comment by itsmattkc** [comment]
_Should_ be addressed with the latest commit, let me know if not
