### ISSUE TITLE
[CI] Migrate to GitHub Actions

### ISSUE THREAD

**Issue by itsmattkc** [sobotka/olive#126]
**Summary**
Switch from our current Travis/AppVeyor CI system to GitHub Actions.

We should see at least the following benefits from this:
- Consolidating our CIs to one service rather than two. Travis CI has virtually no Windows support which necessitates using a second service like AppVeyor as well. Actions should be able to handle all of our deployment platforms.
- CentOS deployment through a docker image. While Actions does not provide CentOS as a platform, it appears we should still be able to deploy by using a CentOS docker image on Ubuntu.
- General convenience with everything being consolidated to GitHub.

Feel free to comment any others.

**Comment by Simran-B** [comment]
Experimental CentOS 7 CI is pretty much working, uploads build artifact but does not create a GitHub release yet: https://github.com/Simran-B/olive-ci

**Comment by Simran-B** [comment]
Matt set up a Windows and macOS workflow using pre-built binaries hosted on the website, and I merged the Linux Docker CI. There's certainly more stuff to improve and we may delete the AppVeyor and Travis configuration, but the migration to GitHub Actions is essentially done.
