### ISSUE TITLE
[BUG] Right Click Context Menu Disabled in Footage Viewer

### ISSUE THREAD

**Issue by ThomasWilshaw** [sobotka/olive#127]
**Platform**
Windows 7 SP1 64 Bit
Intel HD Graphics 4600
Olive 0.2.0-6a50c0a6 (Release build)
Built with Visual Studio 2019 and vcpkg libraries

**Issue**
The right click context menu appears to be missing/disabled in the footage viewer. When I right click nothing happens except a stop symbol (circle with line through) appears briefly.

**Steps to Reproduce**
Create a new sequence and import footage
Double click footage in the project panel to open it in the viewer
Right click in the viewer.

**Comment by itsmattkc** [comment]
I fixed this on my end in `cacheondemand`, let me know if it's fixed for you too

**Comment by ThomasWilshaw** [comment]
Yep that's fixed it, thanks.
