### ISSUE TITLE
[UI DATA FEEDBACK] UI scaling problems on monitors that overscan

### ISSUE THREAD

**Issue by tkoham** [sobotka/olive#131]
**Platform**
CentOS 7, Intel i7 6700k GTX 1070

**Summary**
UI becomes unuseably large on displays that underscan/overscan

**Additional Information / Output**
I use a proofing TV that needs underscan to frame properly. Olive's UI scales properly with every other display I own, but when fullscreened on the TV, the UI suddenly becomes unuseably large.  example attached

![image](https://user-images.githubusercontent.com/13039170/83343712-ec9d1600-a2cb-11ea-981e-a5136e70952d.png)
**
![image](https://user-images.githubusercontent.com/13039170/83343717-fcb4f580-a2cb-11ea-9908-cfdf7721c0c1.png)
**

**Comment by itsmattkc** [comment]
This looks like it thinks the TV is HiDPI? Almost certainly something Qt related. How is the underscan set on the TV/what other parameters are set on it?

**Comment by itsmattkc** [comment]
Is this fixed in 29537fea?
