### ISSUE TITLE
[CRASH] Crash when adding DJI Mavic Mini MP4 files

### ISSUE THREAD

**Issue by maicardi** [sobotka/olive#133]
**Platform**
OS: Ubuntu 20.04
Kernel: 5.4.0-37-generic #41-Ubuntu SMP x86_64 GNU/Linux
Resolution: 2x 1920x1080 + 1x 1024x768
DE: MATE
CPU: Intel i7 8705G
GPU: AMD Radeon RX Vega M GL (disabled) + eGPU NVIDIA GeForce GTX 1060 (running)
RAM: 32GB

**Olive Editor Version**
Olive Editor both 201905021432-1e3cf53+1050~ubuntu19.04.1 from ppa:olive-editor/olive-editor and 0.2.0-49cec970 built with Ninja.

**Summary**
When adding to a sequence every single MP4 file produced by a DJI Mavic Mini drone the program crashes.

**Steps to reproduce**
- Create new project;
- Add MP4 file to the project;
- Create a new sequence;
- Drag the MP4 file from the project to the sequence timeline -> CRASH

**Additional Information / Output**
- This does not happen to other MP4 files like the ones created from the FIMI X3 SE drone or files downloaded from YouTube.
- As appears [in this post](https://www.reddit.com/r/olive/comments/eud71z/olive_video_editor_supports_gopro_session_5_and/), the same happens with files created by DJI Go Pro Session 5.
- The jan/19 snap alpha version c8aec60 refuses to add the MP4 file to the sequence timeline; in the project media files such files appear with a red icon with a "X" sign.
- The typic MP4 files I try to add to Olive Editor are h264 MPEG-4 AVC 2720x1530 25 fps and 29.97 fps.

A test video file which lead to such crashes can be downloaded from Firefox Send until 20/jun/2020 using this URL: https://send.firefox.com/download/5065796192c269d7/#w-Tdl40OPHaNVH9f8S6-NA

**Comment by sobotka** [comment]
Thanks for the report. Is this against the current 0.2.x branch?

**Comment by maicardi** [comment]
> Thanks for the report. Is this against the current 0.2.x branch?

Yes, I have built today from the master branch (0.2.0 078e3545).

**Comment by itsmattkc** [comment]
Fixed as of cbbf1c9149a864b4d838e0d9f78b0f03d37aee2b

**Comment by maicardi** [comment]
> Fixed as of [cbbf1c9](https://github.com/sobotka/olive/commit/cbbf1c9149a864b4d838e0d9f78b0f03d37aee2b)

I can confirm that this have been fixed with such commit.

I will post the solution on Reddit, too.

Thanks a lot for your help.
