### ISSUE TITLE
[TODO] Implement Google Crashpad (or similar)

### ISSUE THREAD

**Issue by itsmattkc** [sobotka/olive#137]
**General TODO Summary**
Implement a more reliable crash reporter than our current crude in-process one.

**Additional Information / Notes**
While our current in-process backtrace generator is better than nothing, it's not perfect. It can't provide any more information than a backtrace and often it doesn't work at all since it's generated by the application itself and the application is often not in a stable state after a crash. A much more reliable solution is an external process that can pick up Olive crashing without being affected itself. Projects like [Google Crashpad](https://chromium.googlesource.com/crashpad/crashpad/) appear to implement something like this, which means we don't have to fabricate our own solution. There may also be other libs that would work as well.

**Comment by Simran-B** [comment]
Matt integrated Google Crashpad for catching segfaults and Breakpad to read the dump and display to the user what is about to be sent:

![image](https://user-images.githubusercontent.com/7819991/93988662-48167680-fd89-11ea-8cb0-27104d8bdb93.png)

The automated builds bundle the necessary binaries crashpad_handler and minidump_stackwalk.
