### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by patryk-m-malinowski** [sobotka/olive#138]
### How to reproduce

1. Open a new session of Olive

create a new sequence:
2. File → New → Sequence
3. Select 1080p for the preset
4. Click 'OK'

5. Edit → Insert                      ,
this will cause the crash

### Frequency

The crash will mostly happen straight away after you click Insert, but sometimes you need to click 'Insert' twice. I never had to do it three times.

### Crash Log of Olive

Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.4.52-1-MANJARO
System: Manjaro Linux (manjaro unknown)

./olive-editor(_ZN5olive13crash_handlerEi+0x112)[0x55f86ddf7882]
/usr/lib/libc.so.6(+0x3c3e0)[0x7feb4630e3e0]
./olive-editor(_ZN5QListISt10shared_ptrIN5olive6StreamEEEC1ERKS4_+0x0)[0x55f86de6a350]
./olive-editor(_ZNK5olive7Footage24get_enabled_stream_flagsEv+0x36)[0x55f86de68e56]
./olive-editor(_ZN5olive14TimelineWidget23FootageToDraggedFootageEPNS_7FootageE+0xa)[0x55f86df0b3aa]
./olive-editor(_ZN5olive14TimelineWidget23FootageToDraggedFootageE5QListIPNS_7FootageEE+0x70)[0x55f86df0d2d0]
./olive-editor(_ZN5olive14TimelineWidget10ImportTool7PlaceAtERK5QListIPNS_7FootageEERKNS_8rationalEb+0x44)[0x55f86def4b94]
./olive-editor(_ZN5olive14TimelineWidget23InsertFootageAtPlayheadERK5QListIPNS_7FootageEE+0x42)[0x55f86df0b4a2]
./olive-editor(_ZN5olive13TimelinePanel6InsertEv+0x45)[0x55f86de63ab5]
/usr/lib/libQt5Core.so.5(+0x2eaa26)[0x7feb46abfa26]
Version: 0cd4edad
Signal: 11

**Comment by itsmattkc** [comment]
Fixed in 0075733da1791bcd641ba1c4cd8a505f0f9a1301
