### ISSUE TITLE
[UI DATA FEEDBACK] Incorrect correlation between parameter editor timeline and sequence timeline

### ISSUE THREAD

**Issue by DaniSeeh** [sobotka/olive#21]
**Platform**
Manjaro Gnome
AMD Ryzen 7 1700x
GTX 1070 8gb
32gb DDR4 RAM
Build: e578ee6

**Summary**
When you place a clip in the timeline, and then go to keyframe it, the keyframe timeline correlates with the sequence timeline while scrubbing, but not with the beginning of the clip. However, even more strangely, the actual keyframes you place do correlate with the beginning of the clip and not the overall timeline.

**Additional Information / Output**
https://www.youtube.com/watch?v=tHLehYtOpe0

There is a link to a quick video of the issue. It may be easier to see than explain. If you see, the parameter editor's timeline always perfectly matches the main timeline as you scrub it, but the key frames actually still match to an individualized timeline like Olive 0.1. Hopefully that is clear.

**Comment by DaniSeeh** [comment]
It isn't a crash. I don't know how to remove that label and there was no category for bugs.

**Comment by sobotka** [comment]
I've added another issue template and label for granularity. Bug class seems too broad to be useful for folks trying to triage?

**Comment by itsmattkc** [comment]
This was actually fixed a while ago in 3399227b3aed6f1f3d8a97e65e649383604af727 but I forgot to close this issue

**Comment by DaniSeeh** [comment]
Eh, still not fixed in 5b48c1c as far as I can tell

**Comment by itsmattkc** [comment]
@DaniSeeh It sort of depends, if a node is connected to multiple clips, it may have multiple time transforms and there's no UI to switch between them yet. However for only one time transform (e.g. have one clip and move it anywhere else) the keyframes should be in the correct place.

**Comment by DaniSeeh** [comment]
Huh... Interesting. I'll post a screenshot
