### ISSUE TITLE
Seeking is broken

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#24]
1. Place a clip on the timeline
2. Click anywhere in the timeline ruler to reposition the playhead
3. Start playback, then pause — the playhead goes back to where you changed the position to
4. Try arrow keys for seeking and get a nice techno sound as Olive repeats one frame worth of audio data jumping to previous/next frame and back :)

All of this happens only after you played the sequence for the first time. You can reposition the playhead as many times as you like. But once you play, you are stuck, my friend :)

**Comment by prokoudine** [comment]
Oh, and this is on commit 4bc5378116771266dad9120ccd22ec446e3dc359

**Comment by itsmattkc** [comment]
Fixed in 1c192100c2462637a438813ad4f32bbee7a7854b
