### ISSUE TITLE
[AUDIOIO] Second audio track not played back

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#26]
**Platform**

Linux 64-bit, Ubuntu 19.10

**Summary**

If you have two audio tracks, only the upper one will play.

This is on latest git, commit e6b484a5239459994273c5a747c9d282f26acd79

**Comment by itsmattkc** [comment]
Should be fixed with the addition of the math node

**Comment by sobotka** [comment]
If a commit in the description features certain trigger words such a "fixes #26", GitHub should auto reference and close I think? Good to keep in mind when the Issue Tracker reopens.
