### ISSUE TITLE
[PIXELS] CM transforms loaded footage incorrectly (?)

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#28]
OpenColorIO related likely. Pixel values aren't making it into the working space in radiometrically linear ratios. Use sample footage GH5 10 bit +2 EV and sample configuration with footage tagged Panasonic VLog / VGamut, and sample the sky. Pixel Sampler reveals hard clamp at 1.0 which might suggest a shader calculation issue.

When using the Math node to duplicate the emission values from the footage, the sampler reveals appropriate +1 EV difference.
![Screenshot from 2020-04-03 10-25-28](https://user-images.githubusercontent.com/59577/78389228-3f41a680-7597-11ea-9e2c-1d023247cb50.png)

**Comment by Corruptinator** [comment]
![image](https://user-images.githubusercontent.com/5027750/78411638-2819ad80-75c5-11ea-9b57-966b4bd7f258.png)

**Comment by sobotka** [comment]
Fixed with 615e227.
