### ISSUE TITLE
[CODEC] Arri Alexa LF ProRes in MXF bombs out Olive

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#29]
**Summary**
Alexa Mini LF footage in a MXF wrapper bombs Olive out. Likely symptomatic of other lower level codec woes from FFMPEG.

**Additional Information / Output**
Arri official footage samples from https://arriwebgate.com/directlink/b043cddb9c4658e0. Sample used where segfault happened was `Alexa_Mini_LF_F003C003_190925_MN99.mxf` although it likely applies to all sample footage there.

**Comment by sobotka** [comment]
Duplicate of #31. I'll merge it to there as there's good information.

**Comment by itsmattkc** [comment]
The only crash I've been able to produce was fixed a while ago, does this still occur on the latest commit?
