### ISSUE TITLE
[PIXELS] Invalid Value When Clicking On Color Picker's View Dropdown.

### ISSUE THREAD

**Issue by Corruptinator** [sobotka/olive#30]
**Windows 10 64 Bit, Ryzen 3900x, RTX 2080 Super**

**When I try to choose View in the Solid Generator's Color Picker, the software freezes and causes the debug to endlessly loop an invalid value:**

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/5027750/78411939-65326f80-75c6-11ea-939a-11fbaad4af95.png)

**Comment by itsmattkc** [comment]
Ahh Qt doesn't accept any RGB values over 1.0. Considering QColor is only used for UI representation, I assume the values should just be clamped before being sent to it.

**Comment by itsmattkc** [comment]
Fixed in d8e0a313750b01dc5d05b14ba17e98989d7fbb50
