### ISSUE TITLE
[CACHE] Cache drops and fails to reconstruct / render

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#32]
**Platform**
Debian Buster

**Summary**
Cache seems to lose sync and fails to display a frame. Results in blackness.
![Screenshot from 2020-04-03 20-51-40](https://user-images.githubusercontent.com/59577/78417994-f3215100-75ec-11ea-9234-685eb19546dc.png)

**Additional Information / Output**
1. Load Arri footage `J001C012_140110_R6MS.mov`
2. Cut into three section and arrange loosely as screenshot.
3. Appears that the third cut on the lower reel fails to update cache properly.

Moving the strip in question while on the lower reel, seems to cause the upper reel content to also lose cache / frames.

**Comment by itsmattkc** [comment]
This seems to have been fixed by addressing the heap corruption from a while ago.
