### ISSUE TITLE
[UI DATA FEEDBACK] Two finger / wheel scroll inverted on Timeline View

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#33]
**Platform**
Debian Buster
**Summary**
Two finger scroll on touchpad appears to be polarity inverted? Up down seems to scroll left to right on the Timeline UI, while left to right scrolls the relevant Timeline panel up and down.

**Comment by itsmattkc** [comment]
Actually not a bug, this is a preference in Preferences > Behavior > Timeline > Invert Timeline Scroll Axes. It defaults to enabled for one-dimensional scroll wheels under the assumption that scrolling the timeline left to right is a more common action than top to bottom (holding Alt will also invert back to normal/switch to left to right scrolling for scroll wheel users).

Whether there's an automatic way to detect touchpads over a standard mouse is another question though.
