### ISSUE TITLE
[CACHE] Caching settings forgotten after quitting the program

### ISSUE THREAD

**Issue by prokoudine** [sobotka/olive#35]
**Platform**

Ubuntu 19.10, 64-bit

Commit 626c50477c4cd83fdd0358844246e88c4f267e81

**Summary**

1. Tools > Preferences > Disk
2. Set 'Cache ahead" to 30 seconds
3. Restart Olive
4. "Cache ahead' is back to 10 seconds (default value)

**Comment by itsmattkc** [comment]
This is actually somewhat intentional, the config saving is disabled at the moment for testing purposes.

**Comment by itsmattkc** [comment]
Enabled in edeeed49ba54ab6272d48f7256ef9600a4282c9b
