### ISSUE TITLE
[PIXELS] Image exporting appears to be non-functional. Maybe just exporting Alpha channel?

### ISSUE THREAD

**Issue by DaniSeeh** [sobotka/olive#46]
**Platform**
Build: ba94aa0
Manjaro Gnome 19
Ryzen 1700x
GTX 1070
32GB RAM
NVIDIA 440 Drivers
**Summary**
Exporting images produces bad results. Possibly just alpha channel. Also image sequence exporting seems completely non-functional as it only exports the first frame.
**Additional Information / Output**
Example:
![Screenshot from 2020-04-30 00-28-26](https://user-images.githubusercontent.com/46905995/80675716-d1e04300-8a7a-11ea-94c0-bd05b3759262.png)
![Sequence](https://user-images.githubusercontent.com/46905995/80675721-d4db3380-8a7a-11ea-832a-7e133f61d091.png)

**Comment by itsmattkc** [comment]
Rolling this into #76
