### ISSUE TITLE
[CODEC] Skewed image import 

### ISSUE THREAD

**Issue by AlexMitchellMus** [sobotka/olive#47]
**Platform**
OS: Arch Linux x86_64 
Host: TM1701 
Kernel: 5.6.7-arch1-1 
Shell: bash 5.0.16 
Resolution: 1920x1080 
DE: GNOME 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: NVIDIA GeForce MX150 
GPU: Intel UHD Graphics 620 

**Summary**
Image input can create a skewed image in Olive.

**Additional Information / Output**
Example screenshot:
![Screenshot from 2020-04-30 15-49-59](https://user-images.githubusercontent.com/12004932/80678694-9a18e000-8afa-11ea-8e16-aec026c08321.png)

Original Image:
https://i.stack.imgur.com/5KvPB.jpg

**Comment by itsmattkc** [comment]
I started running into this last night, it's OIIO related, but weirdly only seems to happen on some setups (maybe has something to do with OIIO version?)

For me, I can confirm it works on both macOS OIIO (from Homebrew) and MinGW OIIO but does NOT work on Vcpkg's OIIO.

MinGW's version is 2.1.12.

**Comment by AlexMitchellMus** [comment]
Arch uses: openimageio 2.1.11.2

FWIW, Homebrew is up to 2.1.13:
https://formulae.brew.sh/formula/openimageio#default

**Comment by itsmattkc** [comment]
Looks like Vcpkg uses 2.1.9, oldest by far.

Could it really be an OIIO bug fixed between 2.1.11 and 2.1.12?

**Comment by AlexMitchellMus** [comment]
The bug doesn't happen on all images. So it makes it hard to work out what is happening. I converted the cat picture into PNG, and TIF, both had the same issue in Olive.

Possibly it could have to do with the image dimensions? But I can't see such a large bug being in any OIIO.

**Comment by itsmattkc** [comment]
Yeah it'll only occur on images where the width is not a multiple of 16. For optimization and compatibility, Olive's buffer widths are always multiples of 16 and OIIO is informed of this, but the skewing happens when OIIO ignores it for whatever reason.

If it is an OIIO bug, we'll just have to do the linesize conversion ourselves. Not a huge deal, just a mild inconvenience.

**Comment by itsmattkc** [comment]
Yep OIIO bug: https://github.com/OpenImageIO/oiio/pull/2487

**Comment by itsmattkc** [comment]
Workaround implemented in 472030f8f0727f06746a40ded72bc414abf299f9
