### ISSUE TITLE
[TODO] Configure optional pixel aspects for footage

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#49]
**General TODO Summary**

Some footage shot with adapters may not report metadata from the adapters.

**Additional Information / Notes**

Anamorphic adapters, for example, will not report the proper aspect ratio, and as such, configuration options are required:
 * For integration with other footage, the pixel aspect should likely be per footage.
 * For an entire project shot with different aspect, the overall project settings should be configurable.

**Comment by itsmattkc** [comment]
Done in fb05594b5097d74bbaac3a2fc62dbe2a5f6ea4a8
