### ISSUE TITLE
[PIXELS][OPENGL] Waveform doesn't display correctly for gaps in the timeline

### ISSUE THREAD

**Issue by ThomasWilshaw** [sobotka/olive#51]
**Platform**
Windows 7 SP1 64 Bit
Intel HD Graphics 4600
Olive 0.2.0-df7f0040 (Debug build)
Built with Visual Studio 2019 and vcpkg libraries

**Summary**
The waveform monitor doesn't work for gaps in the timeline, it should go black but stays as it was on the last frame of the last clip. Also does the same when the cursor reaches the end of the timeline and the viewer goes black.

**Additional Information / Output**
Inserting a solid seems to fix the problem, although I'm not sure I did it correctly.

Screen shot is from an older release but the problem appears to be the same in newer builds.
![image](https://user-images.githubusercontent.com/7781683/80753209-cb0e0a80-8b24-11ea-9764-7dbd728ea604.png)

**Comment by ThomasWilshaw** [comment]
This does appear to also be happening in the latest build (on my system) of Olive. Specifically thats: 

be5e5042

**Comment by itsmattkc** [comment]
Fixed in 9335815d20924aec91201b0713ac98a5e093296c
