### ISSUE TITLE
[TODO] Add Sponsor link to header at GitHub

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#53]
**General TODO Summary**

Sponsor links are available. Enable it.

**Additional Information / Notes**

GitHub added Sponsor links. Enable the link on the primary Olive repository, and sign up https://github.com/sponsors for doubling the sponsorship contributions up to 5000$ USD.

**Comment by Simran-B** [comment]
There is a sponsor link for Patreon meanwhile:

![image](https://user-images.githubusercontent.com/7819991/93988951-9cb9f180-fd89-11ea-8f35-b579f470b6df.png)

@itsmattkc Do you want to add a GitHub option as well? Looks like there is a wait list... Not sure if they still double up contributions. Wasn't that only a thing for the first year when they introduced it?

**Comment by itsmattkc** [comment]
Yeah I couldn't find anything about that either, and yeah looks like they also want a bank account specifically for the organization or a "fiscal host". I think it's more effort than it's worth right now so I'll consider this done for now.

**Comment by Simran-B** [comment]
Found an [official statement](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors#about-the-github-sponsors-matching-fund) that the doubling up is over:

> **Note:** Eligibility for the GitHub Sponsors Matching Fund has passed. Applications received after the January 1, 2020 deadline are not eligible for GitHub Sponsors Matching Fund.
