### ISSUE TITLE
[CODEC] Exports from Square or Anamorphic Aspect Ratios Blank bottom of frame

### ISSUE THREAD

**Issue by tkoham** [sobotka/olive#55]
**Platform**
CentOS 8, Mobile i5-2520

**Summary**
Exporting in "less standard" (web publishing, anamorphic, etc) aspect ratios seems to blank the last few lines of the frame. all files tested are DNxHR HQ at 1080 vertical lines of resolution. at square and 2.39:1 the problem is most noticeable. Doesn't seem to affect standard 16:9 or 4:3 resolutions.

**Additional Information / Output**
Problem I'm describing is pictured here, view full scale to see the line blanking properly
![cubes_1 1 1](https://user-images.githubusercontent.com/13039170/80863171-72d02900-8c48-11ea-8c06-179c04aaa1ca.png)
![cubes_1 2 1](https://user-images.githubusercontent.com/13039170/80863178-79f73700-8c48-11ea-868c-0cd6843b9c68.png)
![rings_1 2 2](https://user-images.githubusercontent.com/13039170/80863211-be82d280-8c48-11ea-846b-f91f15ebef36.png)
![rings_1 1 2](https://user-images.githubusercontent.com/13039170/80863215-c17dc300-8c48-11ea-8baf-61ea801b3698.png)

**Comment by itsmattkc** [comment]
I was under the impression that a2cba8c103b9109833339db71fc6aa6007b82075 fixed this, can you confirm which commit you're on?

**Comment by tkoham** [comment]
I'm in the most recent commit, built it this morning.

**Comment by itsmattkc** [comment]
Which OpenImageIO version are you on?

**Comment by tkoham** [comment]
built using 2.0.10-2 on CentOS 8

**Comment by itsmattkc** [comment]
Is it fixed in 3e57cdac1d412be81d875193953b6d6d2c497b43?

**Comment by tkoham** [comment]
Building now fails with 

```
/home/tyson/Git/olive/app/codec/oiio/oiiodecoder.cpp:234:49: error: ‘OpenImageIO_v2_1’ has not been declared
 void OIIODecoder::FrameToBuffer(FramePtr frame, OpenImageIO_v2_1::ImageBuf *buf)
                                                 ^~~~~~~~~~~~~~~~
/home/tyson/Git/olive/app/codec/oiio/oiiodecoder.cpp:234:76: error: expected ‘,’ or ‘...’ before ‘*’ token
 void OIIODecoder::FrameToBuffer(FramePtr frame, OpenImageIO_v2_1::ImageBuf *buf)
                                                                            ^
/home/tyson/Git/olive/app/codec/oiio/oiiodecoder.cpp:234:6: error: no declaration matches ‘void olive::OIIODecoder::FrameToBuffer(olive::FramePtr, int)’
 void OIIODecoder::FrameToBuffer(FramePtr frame, OpenImageIO_v2_1::ImageBuf *buf)
      ^~~~~~~~~
In file included from /home/tyson/Git/olive/app/codec/oiio/oiiodecoder.cpp:21:
/home/tyson/Git/olive/app/codec/oiio/oiiodecoder.h:51:15: note: candidate is: ‘static void olive::OIIODecoder::FrameToBuffer(olive::FramePtr, OpenImageIO_v2_0::ImageBuf*)’
   static void FrameToBuffer(FramePtr frame, OIIO::ImageBuf* buf);
               ^~~~~~~~~
/home/tyson/Git/olive/app/codec/oiio/oiiodecoder.h:32:7: note: ‘class olive::OIIODecoder’ defined here
 class OIIODecoder : public Decoder
       ^~~~~~~~~
[  9%] Building CXX object app/CMakeFiles/olive-editor.dir/codec/frame.cpp.o
make[2]: *** [app/CMakeFiles/olive-editor.dir/build.make:723: app/CMakeFiles/olive-editor.dir/codec/oiio/oiiodecoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:146: app/CMakeFiles/olive-editor.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by itsmattkc** [comment]
Sorry, try 2d0e5322f21d161e181439d98087b7925c03f078

**Comment by tkoham** [comment]
That seems to have fixed it, Thanks!

**Comment by itsmattkc** [comment]
Excellent, turns out the OpenImageIO `get_pixels()` bug also affected `set_pixels()`. We now implement our workaround for both.
