### ISSUE TITLE
[PIXELS] Set locale to C when loading OCIO configurations

### ISSUE THREAD

**Issue by itsmattkc** [sobotka/olive#88]
**Summary**
A known issue with OCIO's config loading, we'll likely have to implement a workaround in the code to prevent it from failing on non-English systems.

**Comment by sobotka** [comment]
https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/297#issuecomment-505636123

**Comment by itsmattkc** [comment]
911ef782f97b13d9454e4ef3f61dd020967802ce _should_ implement this, but my system uses English locale and was unaffected so I haven't tested it.

**Comment by itsmattkc** [comment]
Confirmed working in 17876410b5c93b84d2ab0a0c168739ff65e1d7a9
