### ISSUE TITLE
[AUDIOIO] Audio on test footage starts after audio timeline region

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#9]
**Platform**
Linux, Debian

**Summary**
Audio commences playback only after the playhead has past the UI region in the timeline. Test footages exhibit this behaviour both on the Panasonic and Fuji X-T30.

**Comment by AlexMitchellMus** [comment]
**Platform**
Linux, Arch

I can confirm this behaviour.

**Comment by itsmattkc** [comment]
Appears to be a Linux exclusive issue (might affect Mac too but doesn't affect Windows). Will do more Linux testing over the next few days.

**Comment by itsmattkc** [comment]
Fixed in 33a85aa0592ca7dcdcfff990a635d5a0e87c8c7c
